### ISSUE TITLE
Tranquil: Missing role names

### ISSUE THREAD

**Issue by ralsei** [monstrousdev/themes#10]
Vaguely self-explanatory. Using Discord 0.0.9, and the latest EnhancedDiscord.

If it's important, I'm additionally using this CSS:
```css
.theme-dark,
.appMount-3VJmYg,
.theme-dark .theme-light {
    --main-color: #88c0d0;
    --primary-color: #2e3440;
    --secondary-color: #3b4252;
    --tertiary-color: #3b4252;
    --quaternary-color: #2e3440;
}
```

![1578541667](https://user-images.githubusercontent.com/16062051/72036549-23b15300-3269-11ea-93c3-5a74f699a0b2.png)
