### ISSUE TITLE
[Black Hole] Problem & Fix with ON/OFF buttons.

### ISSUE THREAD

**Issue by LinUwUxCat** [monstrousdev/themes#22]
Hello, i noticed that the On/Off buttons have a visible container, like this video:

https://user-images.githubusercontent.com/46047705/115749137-16a17000-a397-11eb-9d3c-8fac65975832.mp4

I've talked with people on the BetterDiscord server and a way to fix it would be to set the bd-switch and bd-switch-checked to transparent, instead of blurple, like this:
```css
.bd-switch.bd-switch-checked, .bd-switch { background-color: transparent !important;} 
```
